unique_name: lte-mdt-configuration-and-delivery
object_type: dataset
label: lte-mdt-configuration-and-delivery
connection_id: con1
table: telus-pm-samsung-lte-mdt-configuration-and-delivery-view
incremental:
  column: init_time
  grace_period: 86400s
columns:
- name: ImmediateM1MDTConfigurationCnt_count
  data_type: double
- name: ImmediateM1MDTDeliveryCnt_count
  data_type: double
- name: LoggedMDTCapableUEAvg_count
  data_type: double
- name: LoggedMDTCapableUECnt_count
  data_type: double
- name: LoggedMDTCapableUETot_count
  data_type: double
- name: LoggedMDTConfigurationCnt_count
  data_type: double
- name: LoggedMDTDeliveryCnt_count
  data_type: double
- name: cNum
  data_type: string
- name: family
  data_type: string
- name: gran_period
  data_type: string
- name: init_time
  data_type: datetime
- name: location_str
  data_type: string
- name: ne_id
  data_type: string
- name: ne_name
  data_type: string
- name: sw_version
  data_type: string
- name: system_id
  data_type: string
- name: time_offset
  data_type: string
