unique_name: lte-nb-iot-rrc-connection-reconfiguration
object_type: dataset
label: lte-nb-iot-rrc-connection-reconfiguration
connection_id: telus_pm_samsung_lte_v1
table: telus-pm-samsung-lte-nb-iot-rrc-connection-reconfiguration-view
incremental:
  column: init_time
  grace_period: 86400s
columns:
- name: NBIoT_ConnReconfigAtt_count
  data_type: double
- name: NBIoT_ConnReconfigSucc_count
  data_type: double
- name: NBIoT_cNum
  data_type: string
- name: family
  data_type: string
- name: gran_period
  data_type: string
- name: init_time
  data_type: datetime
- name: location_str
  data_type: string
- name: ne_id
  data_type: string
- name: ne_name
  data_type: string
- name: sw_version
  data_type: string
- name: system_id
  data_type: string
- name: time_offset
  data_type: string
