unique_name: nr-connected-ue-number-configured-with-uplink-only-rohc-fo-3
object_type: dataset
label: nr-connected-ue-number-configured-with-uplink-only-rohc-fo-3
connection_id: telus_test
table: telus-pm-samsung-nr-connected-ue-number-configured-with-uplink-only-rohc-for-sa-view
incremental:
  column: init_time
  grace_period: 86400s
columns:
- name: CPC_ID
  data_type: string
- name: CellIdentity
  data_type: string
- name: UlRohcUeNoAvg_count
  data_type: double
- name: UlRohcUeNoCnt_count
  data_type: double
- name: UlRohcUeNoMax_count
  data_type: double
- name: UlRohcUeNoTot_count
  data_type: double
- name: family
  data_type: string
- name: gNB_ID
  data_type: string
- name: gran_period
  data_type: string
- name: init_time
  data_type: datetime
- name: location_str
  data_type: string
- name: ne_id
  data_type: string
- name: ne_name
  data_type: string
- name: sw_version
  data_type: string
- name: system_id
  data_type: string
- name: time_offset
  data_type: string
