unique_name: nr-rrc-connection-reconfiguration
object_type: dataset
label: nr-rrc-connection-reconfiguration
connection_id: telus_test
table: telus-pm-samsung-nr-rrc-connection-reconfiguration-view
incremental:
  column: init_time
  grace_period: 86400s
columns:
- name: CellIdentity
  data_type: string
- name: ConnReconfigAtt_count
  data_type: double
- name: ConnReconfigSucc_count
  data_type: double
- name: family
  data_type: string
- name: gNB_ID
  data_type: string
- name: gran_period
  data_type: string
- name: init_time
  data_type: datetime
- name: location_str
  data_type: string
- name: ne_id
  data_type: string
- name: ne_name
  data_type: string
- name: sw_version
  data_type: string
- name: system_id
  data_type: string
- name: time_offset
  data_type: string
