unique_name: nr-spcell-change-time-in-case-of-using-rrc-reconfiguratio-1
object_type: dataset
label: nr-spcell-change-time-in-case-of-using-rrc-reconfiguratio-1
connection_id: telus_test
table: telus-pm-samsung-nr-spcell-change-time-in-case-of-using-rrc-reconfiguration-via-srb3-view
incremental:
  column: init_time
  grace_period: 86400s
columns:
- name: EndcRRCTimeSRB3Cnt_count
  data_type: double
- name: EndcRRCTimeSRB3Tot_s
  data_type: double
- name: TgtCellIdentity
  data_type: string
- name: family
  data_type: string
- name: gNB_ID
  data_type: string
- name: gran_period
  data_type: string
- name: init_time
  data_type: datetime
- name: location_str
  data_type: string
- name: ne_id
  data_type: string
- name: ne_name
  data_type: string
- name: sw_version
  data_type: string
- name: system_id
  data_type: string
- name: time_offset
  data_type: string
